-- =====================================================================
-- Tabel: asesmen_keperawatan_anak
-- Untuk form "Assesment Keperawatan Anak" (RMAsesmenKeperawatanAnak),
-- dibuka dari tab "Penilaian Awal" di DlgRawatInap.
-- Satu baris per no_rawat (REPLACE INTO). Semua field teks disimpan TEXT
-- supaya tidak kena batas "Row size too large (>8126)" pada InnoDB,
-- tanpa perlu mengaktifkan Barracuda/DYNAMIC di server.
-- Nama tabel BARU, tidak menimpa penilaian_awal_keperawatan_ranap_anak bawaan.
-- Catatan: kolom TEXT tidak boleh punya DEFAULT (MySQL lama), jadi dibiarkan
-- nullable.
-- =====================================================================
CREATE TABLE IF NOT EXISTS `asesmen_keperawatan_anak` (
  `no_rawat`            VARCHAR(17) NOT NULL,
  `tanggal`            DATE        DEFAULT NULL,
  `jam`                TIME        DEFAULT NULL,
  `ruang`              TEXT,
  -- Data umum
  `kondisi_masuk`      TEXT,
  `via`                TEXT,
  `nadi`               TEXT,
  `respirasi`          TEXT,
  `suhu`               TEXT,
  `spo2`               TEXT,
  `td`                 TEXT,
  `td_posisi`          TEXT,
  `tb`                 TEXT,
  `bb`                 TEXT,
  `gcs_m`              TEXT,
  `gcs_v`              TEXT,
  `gcs_e`              TEXT,
  `gcs_total`          TEXT,
  `diagnosa_masuk`     TEXT,
  `keluhan_utama`      TEXT,
  -- Riwayat tumbuh kembang
  `gigi_pertama`       TEXT,
  `tengkurap`          TEXT,
  `duduk`              TEXT,
  
  `berdiri`            TEXT,
  `berjalan`           TEXT,
  `bicara`             TEXT,
  `baca_tulis`         TEXT,
  `rambut_pubis`       TEXT,
  `mammae`             TEXT,
  `haid_pertama`       TEXT,
  `mental_emosi`       TEXT,
  `jelaskan_kelainan`  TEXT,
  `riwayat_makanan`    TEXT,
  `alergi`             TEXT,
  `alergi_lateks`      TEXT,
  `alergi_obat`        TEXT,
  `snap_alert`         TEXT,
  -- Barang berharga
  `barang_jenis`       TEXT,
  `barang_tindakan`    TEXT,
  -- Riwayat pasien
  `riwayat_pasien`     TEXT,
  `masalah_anastesi`   TEXT,
  `deskripsi_penyakit` TEXT,
  `riwayat_vaksinasi`  TEXT,
  `influenza_12bln`    TEXT,
  `pneumonia_5thn`     TEXT,
  `vaksinasi_lainnya`  TEXT,
  `riwayat_keluarga`   TEXT,
  -- Psikososial
  `tempat_tinggal`     TEXT,
  `aktivitas_psiko`    TEXT,
  `curiga_aniaya`      TEXT,
  `status_emosional`   TEXT,
  `keluarga_terdekat`  TEXT,
  `hubungan_keluarga`  TEXT,
  `telepon`            TEXT,
  `informasi_dari`     TEXT,
  `agama_keyakinan`    TEXT,
  -- Pemeriksaan fisik
  `fisik_mata`         TEXT,
  `fisik_mata_ket`     TEXT,
  `fisik_paru`         TEXT,
  `fisik_paru_ket`     TEXT,
  `fisik_kardio`       TEXT,
  `fisik_kardio_ket`   TEXT,
  `fisik_gastro`       TEXT,
  `fisik_gastro_ket`   TEXT,
  -- Status nutrisi
  `nutrisi_kurus`        TEXT,
  `nutrisi_penurunan_bb` TEXT,
  `nutrisi_kondisi1`     TEXT,
  `nutrisi_kondisi2`     TEXT,
  `nutrisi_penyakit`     TEXT,
  `nutrisi_rujuk`        TEXT,
  `nutrisi_total`        TEXT,
  `fisik_genito`       TEXT,
  `fisik_genito_ket`   TEXT,
  `fisik_neuro`        TEXT,
  `fisik_neuro_ket`    TEXT,
  `fisik_musculo`      TEXT,
  `fisik_musculo_ket`  TEXT,
  -- Resiko kulit
  `kulit_fisik`        TEXT,
  `kulit_mental`       TEXT,
  `kulit_aktivitas`    TEXT,
  `kulit_mobilitas`    TEXT,
  `kulit_inkontinensia` TEXT,
  `kulit_skor`         TEXT,
  `kulit_catatan`      TEXT,
  -- Aktivitas harian
  `adl_kode`           TEXT,
  `adl_aktivitas`      TEXT,
  `adl_skor`           TEXT,
  `adl_rehab`          TEXT,
  -- Faktor resiko jatuh
  `jatuh_usia`         TEXT,
  `jatuh_jk`           TEXT,
  `jatuh_diagnosis`    TEXT,
  `jatuh_kognitif`     TEXT,
  `jatuh_lingkungan`   TEXT,
  `jatuh_respon`       TEXT,
  `jatuh_obat`         TEXT,
  `jatuh_total`        TEXT,
  `jatuh_resiko`       TEXT,
  -- Nyeri
  `nyeri_skala`        TEXT,
  `nyeri_lokasi`       TEXT,
  `nyeri_onset`        TEXT,
  `nyeri_variasi`      TEXT,
  `nyeri_kualitas`     TEXT,
  `nyeri_pemberat`     TEXT,
  `nyeri_pencetus`     TEXT,
  `nyeri_obat`         TEXT,
  `nyeri_efek`         TEXT,
  -- Restraint
  `restraint_pernah`   TEXT,
  `restraint_perlu`    TEXT,
  -- Komunikasi & edukasi
  `komunikasi`         TEXT,
  `bahasa_harian`      TEXT,
  `hambatan_belajar`   TEXT,
  `cara_belajar`       TEXT,
  `tingkat_pendidikan` TEXT,
  `kebutuhan_edukasi`  TEXT,
  -- Discharge planning
  `kriteria_discharge` TEXT,
  `tinggal_dengan`     TEXT,
  `keluarga_perokok`   TEXT,
  `kondisi_rumah`      TEXT,
  `alat_bantu_khusus`  TEXT,
  `rujuk_komunitas`    TEXT,
  -- Resume
  `masalah_keperawatan` TEXT,
  `rencana_keperawatan` TEXT,
  -- TTD
  `tgl_ttd`            DATE        DEFAULT NULL,
  `jam_ttd`            TIME        DEFAULT NULL,
  `nik`                VARCHAR(20) DEFAULT NULL,
  `kd_dokter`          VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`no_rawat`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
